default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: word-gen_development

test:
  <<: *default
  database: word-gen_test

production:
  <<: *default
  database: word-gen_production
